Added script for image retiral
ocp-power-automation/infra pull request #29
Opened 2020-10-16 12:37 UTC by Shilpi-Das1

Issue Link: https://github.ibm.com/redstack-power/project-mgmt/issues/878
```
**Output:**
image_retiral.py -m image_retiral_manifest.yaml -r "us-south" -k <apiKey> -
i "crn:v1:bluemix:public:cloud-object-storage:global:a/65b64c1f1c29460e8c2e4bbfbd893c2c:8aeefa98-c07b-4d22-aa7a-1694374ae275::"

Cos configuration Key                     Value
Last Updated            Friday, October 16 2020 at 18:04:12
Default Region          us-south
Download Location       C:\Users\ShilpiDas\Downloads
CRN                     crn:v1:bluemix:public:cloud-object-storage:global:a/65b64c1f1c29460e8c2e4bbfbd893c2c:8aeefa98-c07b-4d22-aa7a-1694374ae275::
AccessKeyID
SecretAccessKey
Authentication Method   IAM
URL Style               VHost
Service Endpoint

Image: centos-82-mkumatag.ova.gz not copied FAILED
The specified key does not exist.

Copied centos-82-10072020.ova.gz from ocp4-images-bucket to ocp4-images-bucket-retired
Deleted centos-82-10072020.ova.gz from ocp4-images-bucket 
```

2020-10-16 12:37 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/29#" title="Author self-approved">Shilpi-Das1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sudeeshjohn**
You can assign the PR to them by writing `/assign @sudeeshjohn` in a comment when ready.

The full list of commands accepted by this bot can be found [here](?repo=ocp-power-automation%2Finfra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sudeeshjohn"]} -->

2020-10-16 14:36 UTC, Shilpi-Das1 commented
@sudeeshjohn @mkumatag Please review the code changes

2020-10-16 14:36 UTC, Shilpi-Das1 commented
/assign @Shilpi-Das1

2020-10-16 14:37 UTC, Shilpi-Das1 commented
/cc @mkumatag @sudeeshjohn

2020-11-12 07:44 UTC, bpradipt commented
@sudeeshjohn @mkumatag please review it

2020-11-12 10:33 UTC, mkumatag requested changes
overall looks okay except those error checks

2020-11-12 10:33 UTC, mkumatag commented on scripts/images/image_retiral.py
> +            out, err, ret = exec_cmd(["ibmcloud", "cos", "object-copy", "--bucket", destination_bucket,
I don't see out and err variables aren't used anywhere in this function scope!

2020-11-12 10:33 UTC, mkumatag commented on scripts/images/image_retiral.py
> +    out, err, ret = exec_cmd("ibmcloud cos config list")
and err and ret are not used in the function scope

2020-11-12 10:33 UTC, mkumatag commented on scripts/images/image_retiral.py
> +    retire_images(args.image_retiral_manifest)
no error check for the above 3 function calls

2020-11-12 10:33 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/29#" title="Author self-approved">Shilpi-Das1</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sudeeshjohn** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sudeeshjohn` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Finfra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sudeeshjohn"]} -->

2020-11-13 05:05 UTC, Shilpi-Das1 commented
@mkumatag Addressed all review comments. Please review that

2020-11-13 06:04 UTC, mkumatag commented
/lgtm
/hold for others review
/approve

2020-11-13 06:04 UTC, ltccci commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/29#issuecomment-726542082" title="Approved">mkumatag</a>*, *<a href="https://github.com/ocp-power-automation/infra/pull/29#" title="Author self-approved">Shilpi-Das1</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Finfra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-01 12:12 UTC, closed without merging